// This file was generated by a custom prisma generator, do not edit manually.
export const app_settings_keys = {
  company_name: "company_name",
  company_address_road: "company_address_road",
  company_address_city: "company_address_city",
  company_address_postal_code: "company_address_postal_code",
  company_address_country: "company_address_country",
  company_default_vat: "company_default_vat",
} as const;

export type app_settings_keys = (typeof app_settings_keys)[keyof typeof app_settings_keys];

export const crm_company_size = {
  tiny: "tiny",
  small: "small",
  medium: "medium",
  big: "big",
  large: "large",
  huge: "huge",
} as const;

export type crm_company_size = (typeof crm_company_size)[keyof typeof crm_company_size];

export const unit_of_work = {
  unit: "unit",
  kilogram: "kilogram",
  gram: "gram",
  liter: "liter",
  centiliter: "centiliter",
  milliliter: "milliliter",
  meter: "meter",
  centimeter: "centimeter",
  millimeter: "millimeter",
  c_box: "c_box",
  c_bottle_liter: "c_bottle_liter",
  c_bottle_centiliter: "c_bottle_centiliter",
  c_bottle_milliliter: "c_bottle_milliliter",
} as const;

export type unit_of_work = (typeof unit_of_work)[keyof typeof unit_of_work];

export const payment_method = {
  cash: "cash",
  bank_transfer: "bank_transfer",
  credit_card: "credit_card",
  check: "check",
  paypal: "paypal",
  other: "other",
} as const;

export type payment_method = (typeof payment_method)[keyof typeof payment_method];

export const payment_rule = {
  immediate: "immediate",
  on_receipt: "on_receipt",
  on_delivery: "on_delivery",
  on_order: "on_order",
  on_invoice: "on_invoice",
  on_invoice_30: "on_invoice_30",
  on_invoice_60: "on_invoice_60",
} as const;

export type payment_rule = (typeof payment_rule)[keyof typeof payment_rule];

export const scm_order_state = {
  draft: "draft",
  quotation: "quotation",
  sent: "sent",
  acknowledged: "acknowledged",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export type scm_order_state = (typeof scm_order_state)[keyof typeof scm_order_state];

export const scm_manufacturing_order_state = {
  draft: "draft",
  ready: "ready",
  in_progress: "in_progress",
  completed: "completed",
  cancelled: "cancelled",
} as const;

export type scm_manufacturing_order_state = (typeof scm_manufacturing_order_state)[keyof typeof scm_manufacturing_order_state];

export const permission = {
  r: "r",
  rc: "rc",
  ru: "ru",
  rcu: "rcu",
  rcud: "rcud",
} as const;

export type permission = (typeof permission)[keyof typeof permission];

export const user_settings_keys = {
  app_language: "app_language",
  app_menu_left: "app_menu_left",
  app_pages_top_of_table: "app_pages_top_of_table",
} as const;

export type user_settings_keys = (typeof user_settings_keys)[keyof typeof user_settings_keys];
